import React from "react";
import { Breadcrumb } from "../../components/common/Breadcrumb";
import { Leaf, Award, HeartHandshake, ShieldCheck } from "lucide-react";
export const AboutPage = () => {
  return /* @__PURE__ */ React.createElement("div", { className: "flex flex-col gap-10 pb-12" }, /* @__PURE__ */ React.createElement(Breadcrumb, { items: [{ label: "About Us" }] }), /* @__PURE__ */ React.createElement("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-10 items-center" }, /* @__PURE__ */ React.createElement("div", { className: "flex flex-col gap-4" }, /* @__PURE__ */ React.createElement("span", { className: "text-xs font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest flex items-center gap-1.5" }, /* @__PURE__ */ React.createElement(Leaf, { className: "w-4 h-4" }), " Welcome To EcoBazar"), /* @__PURE__ */ React.createElement("h1", { className: "text-3xl sm:text-4xl font-black text-slate-900 dark:text-slate-100 leading-tight" }, "Connecting Conscious Consumers With 100% Certified Organic Harvests"), /* @__PURE__ */ React.createElement("p", { className: "text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed" }, "Founded in 2023, EcoBazar was born out of a simple mission: to make organic, non-GMO food and sustainable living products accessible, transparent, and affordable for every home."), /* @__PURE__ */ React.createElement("p", { className: "text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed" }, "We partner directly with certified local organic farmers and eco-conscious vendors to eliminate unnecessary middlemen, ensuring fair pay for growers and daily crisp freshness for customers.")), /* @__PURE__ */ React.createElement("div", { className: "relative rounded-3xl overflow-hidden shadow-soft-lg" }, /* @__PURE__ */ React.createElement(
    "img",
    {
      src: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80",
      alt: "Organic Farm",
      className: "w-full h-80 sm:h-96 object-cover"
    }
  ))), /* @__PURE__ */ React.createElement("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-6 pt-6 border-t border-slate-200 dark:border-slate-800" }, /* @__PURE__ */ React.createElement("div", { className: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-soft flex flex-col gap-3" }, /* @__PURE__ */ React.createElement("div", { className: "p-3 bg-emerald-100 dark:bg-emerald-950 text-emerald-600 rounded-2xl w-max" }, /* @__PURE__ */ React.createElement(Award, { className: "w-6 h-6" })), /* @__PURE__ */ React.createElement("h3", { className: "text-base font-bold text-slate-900 dark:text-slate-100" }, "100% Certified Organic"), /* @__PURE__ */ React.createElement("p", { className: "text-xs text-slate-500 leading-relaxed" }, "Every fruit, vegetable, and grain is rigorously tested for organic compliance and zero chemical pesticides.")), /* @__PURE__ */ React.createElement("div", { className: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-soft flex flex-col gap-3" }, /* @__PURE__ */ React.createElement("div", { className: "p-3 bg-emerald-100 dark:bg-emerald-950 text-emerald-600 rounded-2xl w-max" }, /* @__PURE__ */ React.createElement(HeartHandshake, { className: "w-6 h-6" })), /* @__PURE__ */ React.createElement("h3", { className: "text-base font-bold text-slate-900 dark:text-slate-100" }, "Direct Farmer Partnerships"), /* @__PURE__ */ React.createElement("p", { className: "text-xs text-slate-500 leading-relaxed" }, "We support sustainable local agriculture by providing fair pricing and long-term contracts to our organic farming partners.")), /* @__PURE__ */ React.createElement("div", { className: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-soft flex flex-col gap-3" }, /* @__PURE__ */ React.createElement("div", { className: "p-3 bg-emerald-100 dark:bg-emerald-950 text-emerald-600 rounded-2xl w-max" }, /* @__PURE__ */ React.createElement(ShieldCheck, { className: "w-6 h-6" })), /* @__PURE__ */ React.createElement("h3", { className: "text-base font-bold text-slate-900 dark:text-slate-100" }, "Zero Plastic Logistics"), /* @__PURE__ */ React.createElement("p", { className: "text-xs text-slate-500 leading-relaxed" }, "Our delivery boxes are 100% biodegradable, recycled, and eco-friendly to protect the environment."))));
};
